apiVersion: v1
kind: Service
metadata:
  name: {{ include "hello-world.fullname" . }}
spec:
  type: LoadBalancer
  selector:
    app: {{ include "hello-world.name" . }}
  ports:
    - port: 80
      targetPort: 8080
