apiVersion: v2
name: hello-world
version: 0.1.0
description: Hello World with Redis subchart
appVersion: "1.0"

dependencies:
  - name: redis
    version: 18.1.2
    repository: https://charts.bitnami.com/bitnami
