name: Build & Deploy App

on:
  push:
    branches: [ master ]
    paths:
      - 'app/**'
      - 'k8s/hello-world-chart/**'

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Docker login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/hello-world-app:latest ./app
          docker push ${{ secrets.DOCKER_USERNAME }}/hello-world-app:latest

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Update kubeconfig
        run: aws eks update-kubeconfig --region us-east-1 --name eks-hello-world

      - name: Deploy using Helm
        run: |
          helm upgrade --install hello ./k8s/hello-world-chart \
            --set image.repository=${{ secrets.DOCKER_USERNAME }}/hello-world-app \
            --set image.tag=latest

